/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug?: Slug;
  tagline: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category:
    | "cleaning"
    | "photography"
    | "social-content"
    | "tours-experiences"
    | "food-drink"
    | "hospitality-days-out";
  description: string;
  href: string;
  featured?: boolean;
  profileIntro?: string;
  profileBody?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type PartnersPage = {
  _id: string;
  _type: "partnersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroBadge?: string;
  heroHeading: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  introParagraph1?: string;
  introParagraph2?: string;
  introParagraph3?: string;
  tiersEyebrow?: string;
  tiersHeading?: string;
  tiers?: Array<{
    title: string;
    body: string;
    _type: "tier";
    _key: string;
  }>;
  tiersNote?: string;
  whoWeWantEyebrow?: string;
  whoWeWantHeading?: string;
  whoWeWantCategories?: Array<{
    title: string;
    body: string;
    tag:
      | "cleaning"
      | "photography"
      | "social-content"
      | "tours-experiences"
      | "food-drink"
      | "hospitality-days-out";
    _type: "whoWeWantCategory";
    _key: string;
  }>;
  spotlightHeading?: string;
  spotlightBody?: string;
  spotlightImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  directoryEyebrow?: string;
  directoryHeading?: string;
  becomePartnerEyebrow?: string;
  becomePartnerHeading?: string;
  becomePartnerIntro?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroBadge?: string;
  heroHeading: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  introParagraph1?: string;
  introParagraph2?: string;
  introParagraph3?: string;
  whatWeDoEyebrow?: string;
  whatWeDoHeading?: string;
  whatWeDoItems?: Array<{
    title: string;
    body: string;
    _type: "whatWeDoItem";
    _key: string;
  }>;
  coverageEyebrow?: string;
  coverageHeading?: string;
  coverageBody?: string;
  coverageImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  regions?: Array<{
    name: string;
    status: string;
    muted?: boolean;
    _type: "region";
    _key: string;
  }>;
  staysHeading?: string;
  featuredStays?: Array<{
    name: string;
    href: string;
    description: string;
    _type: "featuredStay";
    _key: string;
  }>;
  teamEyebrow?: string;
  teamHeading?: string;
  teamIntro?: string;
  teamMembers?: Array<{
    name: string;
    title: string;
    plainTitle: string;
    bio: string;
    photo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "teamMember";
    _key: string;
  }>;
  workWithUsEyebrow?: string;
  workWithUsHeading?: string;
  workWithUsIntro?: string;
  workWithUsCategories?: Array<{
    title: string;
    body: string;
    _type: "workCategory";
    _key: string;
  }>;
  workWithUsPartnerNote?: string;
  workWithUsContactLine?: string;
  ownershipHeading?: string;
  ownershipBody?: string;
  ownershipCroLinkLabel?: string;
  ownershipCroLinkUrl?: string;
  reachUsHeading?: string;
  reachUsEmail?: string;
  reachUsWhatsapp?: string;
  reachUsWhatsappUrl?: string;
  reachUsInstagramHandle?: string;
  reachUsInstagramUrl?: string;
  faqHeading?: string;
  faqs?: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type CorporateStaysPage = {
  _id: string;
  _type: "corporateStaysPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroBadge?: string;
  heroHeading: string;
  heroBody?: string;
  heroPrimaryCtaLabel?: string;
  heroSecondaryCtaLabel?: string;
  heroFacts?: Array<string>;
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  whoEyebrow?: string;
  whoHeading?: string;
  whoBody?: string;
  whoCards?: Array<{
    title: string;
    body: string;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    _type: "whoCard";
    _key: string;
  }>;
  howEyebrow?: string;
  howHeading?: string;
  howBody?: string;
  howSteps?: Array<{
    title: string;
    body: string;
    _type: "howStep";
    _key: string;
  }>;
  coverageEyebrow?: string;
  coverageHeading?: string;
  coverageAreas?: Array<{
    county: string;
    live?: boolean;
    body: string;
    _type: "coverageArea";
    _key: string;
  }>;
  coverageNote?: string;
  includedEyebrow?: string;
  includedHeading?: string;
  includedFeatures?: Array<{
    title: string;
    body: string;
    icon: "sofa" | "wifi" | "contact" | "clipboard";
    _type: "includedFeature";
    _key: string;
  }>;
  partnerEyebrow?: string;
  partnerHeading?: string;
  partnerBody?: string;
  partnerCtaLabel?: string;
  partnerCtaUrl?: string;
  faqEyebrow?: string;
  faqHeading?: string;
  faqs?: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }>;
  closingHeading?: string;
  closingBody?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type PropertyPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "propertyPage";
};

export type AddOn = {
  _id: string;
  _type: "addOn";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  description?: string;
  price: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  properties: Array<
    {
      _key: string;
    } & PropertyPageReference
  >;
  enabled?: boolean;
};

export type AreaGuideReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "areaGuide";
};

export type LandingPage = {
  _id: string;
  _type: "landingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  heroEyebrow?: string;
  heroHeadline: string;
  heroSubtext?: string;
  heroTags?: Array<string>;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  primaryCtaLabel?: string;
  primaryCtaUrl?: string;
  secondaryCtaLabel?: string;
  secondaryCtaUrl?: string;
  marqueeItems?: Array<string>;
  distanceStat?: string;
  distanceLabel?: string;
  destinationName?: string;
  distanceText?: string;
  geographyHeading?: string;
  proximityStats?: Array<{
    value: string;
    label: string;
    _type: "proximityStat";
    _key: string;
  }>;
  directBookingBadge?: string;
  directBookingHeadline?: string;
  directBookingText?: string;
  directBookingSavingsPercent?: number;
  directBookingComparisonNote?: string;
  featuredProperty?: PropertyPageReference;
  infoSections?: Array<{
    eyebrow?: string;
    heading?: string;
    body?: string;
    layout?: "cards" | "photoGrid";
    items?: Array<{
      title?: string;
      description?: string;
      tag?: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      link?: string;
      _type: "infoItem";
      _key: string;
    }>;
    _type: "infoSection";
    _key: string;
  }>;
  pricingTiers?: Array<{
    amount: string;
    label: string;
    _type: "pricingTier";
    _key: string;
  }>;
  pricingNote?: string;
  pricingLink?: string;
  pricingLinkLabel?: string;
  itineraryEyebrow?: string;
  itineraryHeading?: string;
  itineraryText?: string;
  itineraryDays?: Array<{
    dayLabel: string;
    items?: Array<{
      time?: string;
      title: string;
      description?: string;
      _type: "itineraryItem";
      _key: string;
    }>;
    _type: "itineraryDay";
    _key: string;
  }>;
  relatedAreaGuide?: AreaGuideReference;
  finalCtaHeadline?: string;
  finalCtaText?: string;
  finalCtaSecondaryLabel?: string;
  finalCtaSecondaryUrl?: string;
  stickyBarEnabled?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type CountyPricingStats = {
  _id: string;
  _type: "countyPricingStats";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  county:
    | "Carlow"
    | "Cavan"
    | "Clare"
    | "Cork"
    | "Donegal"
    | "Dublin"
    | "Galway"
    | "Kerry"
    | "Kildare"
    | "Kilkenny"
    | "Laois"
    | "Leitrim"
    | "Limerick"
    | "Longford"
    | "Louth"
    | "Mayo"
    | "Meath"
    | "Monaghan"
    | "Offaly"
    | "Roscommon"
    | "Sligo"
    | "Tipperary"
    | "Waterford"
    | "Westmeath"
    | "Wexford"
    | "Wicklow"
    | "Antrim"
    | "Armagh"
    | "Down"
    | "Fermanagh"
    | "Derry / Londonderry"
    | "Tyrone";
  live: boolean;
  adr: number;
  occupancy: number;
  annualRevenue: number;
  statsSourceNote: string;
  realExample?: {
    propertyName: string;
    propertyLocation: string;
    beforeLabel: string;
    beforeOccupancy: number;
    afterLabel: string;
    afterOccupancy: number;
    note: string;
  };
  drivers?: Array<string>;
  faqs?: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }>;
};

export type TermsPage = {
  _id: string;
  _type: "termsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  lastUpdated?: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type PrivacyPolicyPage = {
  _id: string;
  _type: "privacyPolicyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  lastUpdated?: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type AudienceTabs = {
  _id: string;
  _type: "audienceTabs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow: string;
  tabs: Array<{
    label: string;
    heading: string;
    body: string;
    checklist: Array<string>;
    _type: "audienceTab";
    _key: string;
  }>;
};

export type HostsModule = {
  _id: string;
  _type: "hostsModule";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading: string;
  body?: string;
  commissionRate: number;
  commissionLabel?: string;
  commissionSuffix?: string;
  commissionNote?: string;
  ctaLabel?: string;
  ctaUrl?: string;
  stepperEyebrow?: string;
  stepperHeading?: string;
  steps: Array<{
    title: string;
    bullets: Array<string>;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    _type: "step";
    _key: string;
  }>;
  marqueeHeading?: string;
  marqueeSubtext?: string;
};

export type HeroSection = {
  _id: string;
  _type: "heroSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading: string;
  body?: string;
  subBody?: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  primaryCtaLabel?: string;
  primaryCtaUrl?: string;
  secondaryCtaLabel?: string;
  secondaryCtaUrl?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  guestNavLinks?: Array<{
    label: string;
    href: string;
    _type: "navLink";
    _key: string;
  }>;
  landlordNavLinks?: Array<{
    label: string;
    href: string;
    _type: "navLink";
    _key: string;
  }>;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tagline?: string;
  columns?: Array<{
    title: string;
    links?: Array<{
      label: string;
      href: string;
      _type: "footerLink";
      _key: string;
    }>;
    _type: "footerColumn";
    _key: string;
  }>;
  copyrightText?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  defaultSeoTitle?: string;
  defaultSeoDescription?: string;
  defaultSeoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  businessName?: string;
  contactEmail?: string;
  bookingSubdomainUrl?: string;
  socialLinks?: Array<{
    platform:
      | "instagram"
      | "facebook"
      | "tiktok"
      | "linkedin"
      | "x"
      | "youtube"
      | "tripadvisor"
      | "whatsapp";
    url: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type LandlordPage = {
  _id: string;
  _type: "landlordPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  heroStatement: string;
  proofPoints?: Array<string>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  faqs?: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }>;
  ctaLabel?: string;
  ctaUrl?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type BlogPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPost";
};

export type AreaGuide = {
  _id: string;
  _type: "areaGuide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  areaName: string;
  slug: Slug;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  introduction: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  thingsToDo?: Array<{
    title: string;
    category: "Explore" | "Things to Do" | "Food" | "Transport";
    tag?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    link?: string;
    _type: "activity";
    _key: string;
  }>;
  travelNotes?: Array<{
    label: string;
    description: string;
    _type: "travelNote";
    _key: string;
  }>;
  faqs?: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }>;
  featuredProperties?: Array<
    {
      _key: string;
    } & PropertyPageReference
  >;
  relatedBlogPosts?: Array<
    {
      _key: string;
    } & BlogPostReference
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt?: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  publishedAt: string;
  author?: {
    name?: string;
    role?: string;
    avatar?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  tags?: Array<string>;
  relatedAreaGuides?: Array<
    {
      _key: string;
    } & AreaGuideReference
  >;
  promotedProperty?: PropertyPageReference;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type PropertyPage = {
  _id: string;
  _type: "propertyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  location: string;
  locationLink?: string;
  shortDescription?: string;
  fullDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  roomTypes?: Array<{
    name: string;
    roomId?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    bedConfiguration?: string;
    guests: number;
    _type: "roomType";
    _key: string;
  }>;
  amenities?: Array<string>;
  sleeps?: number;
  priceLabel?: string;
  bedrooms?: number;
  beds?: number;
  bathrooms?: number;
  propertyType?:
    | "House"
    | "Apartment"
    | "Cottage"
    | "Cabin"
    | "Villa"
    | "Bungalow"
    | "Townhouse";
  reviewScore?: number;
  reviewCount?: number;
  reviewCategories?: Array<{
    label: string;
    value: number;
    _type: "reviewCategory";
    _key: string;
  }>;
  faqs?: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }>;
  relatedAreaGuides?: Array<
    {
      _key: string;
    } & AreaGuideReference
  >;
  galleryPromotion?: {
    enabled?: boolean;
    highlights?: Array<{
      headline: string;
      description: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
      };
      supportingImages?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
        _key: string;
      }>;
      ctaLabel: string;
      ctaHref?: string;
      _type: "highlight";
      _key: string;
    }>;
    delaySeconds?: number;
    autoplaySeconds?: number;
  };
  uplistingPropertySlug: string;
  uplistingPropertyId?: number;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Partner
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | PartnersPage
  | AboutPage
  | CorporateStaysPage
  | PropertyPageReference
  | AddOn
  | AreaGuideReference
  | LandingPage
  | CountyPricingStats
  | TermsPage
  | PrivacyPolicyPage
  | AudienceTabs
  | HostsModule
  | HeroSection
  | Navigation
  | Footer
  | SiteSettings
  | LandlordPage
  | BlogPostReference
  | AreaGuide
  | BlogPost
  | SanityFileAssetReference
  | PropertyPage
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current)] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    coverImage,    publishedAt,    author,    tags  }
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  publishedAt: string;
  author: {
    name?: string;
    role?: string;
    avatar?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  } | null;
  tags: Array<string> | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: LANDLORD_BLOG_POSTS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current) && "landlord" in tags] | order(publishedAt desc) [0...3] {    _id,    title,    "slug": slug.current,    excerpt,    coverImage,    publishedAt,    author,    tags  }
export type LANDLORD_BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  publishedAt: string;
  author: {
    name?: string;
    role?: string;
    avatar?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  } | null;
  tags: Array<string> | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: BLOG_POST_QUERY
// Query: *[_type == "blogPost" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    excerpt,    coverImage,    body,    publishedAt,    author,    tags,    relatedAreaGuides[]-> {      _id,      areaName,      "slug": slug.current,      heroImage    },    promotedProperty-> {      _id,      name,      "slug": slug.current,      location,      shortDescription,      priceLabel,      "coverImage": gallery[0]    },    "relatedPosts": *[_type == "blogPost" && defined(slug.current) && _id != ^._id] | order(publishedAt desc) [0...3] {      _id,      title,      "slug": slug.current,      coverImage,      publishedAt    },      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type BLOG_POST_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  publishedAt: string;
  author: {
    name?: string;
    role?: string;
    avatar?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  } | null;
  tags: Array<string> | null;
  relatedAreaGuides: Array<{
    _id: string;
    areaName: string;
    slug: string;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  }> | null;
  promotedProperty: {
    _id: string;
    name: string;
    slug: string;
    location: string;
    shortDescription: string | null;
    priceLabel: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
      _key: string;
    } | null;
  } | null;
  relatedPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    publishedAt: string;
  }>;
  seo: {
    title: string;
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PROPERTY_PAGES_QUERY
// Query: *[_type == "propertyPage" && defined(slug.current)] | order(name asc) {    _id,    name,    "slug": slug.current,    location,    shortDescription,    sleeps,    "coverImage": gallery[0],    uplistingPropertySlug,    roomTypes[] {      name,      roomId,      image,      bedConfiguration,      guests    }  }
export type PROPERTY_PAGES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  location: string;
  shortDescription: string | null;
  sleeps: number | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  } | null;
  uplistingPropertySlug: string;
  roomTypes: Array<{
    name: string;
    roomId: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    bedConfiguration: string | null;
    guests: number;
  }> | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: PROPERTY_PAGE_QUERY
// Query: *[_type == "propertyPage" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    location,    locationLink,    shortDescription,    fullDescription,    gallery,    galleryPromotion {      enabled,      highlights[] {        headline,        description,        image {          ...,          alt        },        supportingImages[] {          ...,          alt        },        ctaLabel,        ctaHref      },      delaySeconds,      autoplaySeconds    },    "videoUrl": video.asset->url,    "videoMimeType": video.asset->mimeType,    roomTypes,    amenities,    sleeps,    priceLabel,    bedrooms,    beds,    bathrooms,    propertyType,    reviewScore,    reviewCount,    reviewCategories,    uplistingPropertySlug,    uplistingPropertyId,    faqs,    relatedAreaGuides[]-> {      _id,      areaName,      "slug": slug.current,      heroImage,      introduction    },      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type PROPERTY_PAGE_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  location: string;
  locationLink: string | null;
  shortDescription: string | null;
  fullDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }> | null;
  galleryPromotion: {
    enabled: boolean | null;
    highlights: Array<{
      headline: string;
      description: string;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
      } | null;
      supportingImages: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
        _key: string;
      }> | null;
      ctaLabel: string;
      ctaHref: string | null;
    }> | null;
    delaySeconds: number | null;
    autoplaySeconds: number | null;
  } | null;
  videoUrl: string | null;
  videoMimeType: string | null;
  roomTypes: Array<{
    name: string;
    roomId?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    bedConfiguration?: string;
    guests: number;
    _type: "roomType";
    _key: string;
  }> | null;
  amenities: Array<string> | null;
  sleeps: number | null;
  priceLabel: string | null;
  bedrooms: number | null;
  beds: number | null;
  bathrooms: number | null;
  propertyType:
    | "Apartment"
    | "Bungalow"
    | "Cabin"
    | "Cottage"
    | "House"
    | "Townhouse"
    | "Villa"
    | null;
  reviewScore: number | null;
  reviewCount: number | null;
  reviewCategories: Array<{
    label: string;
    value: number;
    _type: "reviewCategory";
    _key: string;
  }> | null;
  uplistingPropertySlug: string;
  uplistingPropertyId: number | null;
  faqs: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }> | null;
  relatedAreaGuides: Array<{
    _id: string;
    areaName: string;
    slug: string;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    introduction: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  }> | null;
  seo: {
    title: string;
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PROPERTY_BOOKING_QUERY
// Query: *[_type == "propertyPage" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    location,    sleeps,    "coverImage": gallery[0],    uplistingPropertyId,    "addOns": *[_type == "addOn" && enabled != false && references(^._id)] {      _id,      name,      description,      price,      image    }  }
export type PROPERTY_BOOKING_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  location: string;
  sleeps: number | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  } | null;
  uplistingPropertyId: number | null;
  addOns: Array<{
    _id: string;
    name: string;
    description: string | null;
    price: number;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: AREA_GUIDES_QUERY
// Query: *[_type == "areaGuide" && defined(slug.current)] | order(areaName asc) {    _id,    areaName,    "slug": slug.current,    heroImage,    introduction  }
export type AREA_GUIDES_QUERY_RESULT = Array<{
  _id: string;
  areaName: string;
  slug: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  introduction: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: AREA_GUIDE_QUERY
// Query: *[_type == "areaGuide" && slug.current == $slug][0] {    _id,    areaName,    "slug": slug.current,    heroImage,    introduction,    thingsToDo,    travelNotes,    faqs,    featuredProperties[]-> {      _id,      name,      "slug": slug.current,      location,      shortDescription,      sleeps,      "coverImage": gallery[0],      "gallery": gallery[0...3],      uplistingPropertySlug    },    "relatedBlogPosts": *[_type == "blogPost" && references(^._id)] {      _id,      title,      "slug": slug.current,      excerpt,      coverImage    },      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type AREA_GUIDE_QUERY_RESULT = {
  _id: string;
  areaName: string;
  slug: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  introduction: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  thingsToDo: Array<{
    title: string;
    category: "Explore" | "Food" | "Things to Do" | "Transport";
    tag?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    link?: string;
    _type: "activity";
    _key: string;
  }> | null;
  travelNotes: Array<{
    label: string;
    description: string;
    _type: "travelNote";
    _key: string;
  }> | null;
  faqs: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }> | null;
  featuredProperties: Array<{
    _id: string;
    name: string;
    slug: string;
    location: string;
    shortDescription: string | null;
    sleeps: number | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
      _key: string;
    } | null;
    gallery: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
      _key: string;
    }> | null;
    uplistingPropertySlug: string;
  }> | null;
  relatedBlogPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  }>;
  seo: {
    title: string;
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: LANDLORD_PAGE_QUERY
// Query: *[_type == "landlordPage" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    heroStatement,    proofPoints,    body,    faqs,    ctaLabel,    ctaUrl,      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type LANDLORD_PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  heroStatement: string;
  proofPoints: Array<string> | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  faqs: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }> | null;
  ctaLabel: string | null;
  ctaUrl: string | null;
  seo: {
    title: string;
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: LANDLORD_PAGES_QUERY
// Query: *[_type == "landlordPage" && defined(slug.current)] | order(_createdAt asc) {    _id,    title,    "slug": slug.current,    heroStatement,    proofPoints,    body,    faqs,    ctaLabel,    ctaUrl,      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type LANDLORD_PAGES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  heroStatement: string;
  proofPoints: Array<string> | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  faqs: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }> | null;
  ctaLabel: string | null;
  ctaUrl: string | null;
  seo: {
    title: string;
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: AUDIENCE_TABS_QUERY
// Query: *[_type == "audienceTabs" && _id == "audienceTabs"][0] {    eyebrow,    tabs[] {      label,      heading,      body,      checklist    }  }
export type AUDIENCE_TABS_QUERY_RESULT = {
  eyebrow: string;
  tabs: Array<{
    label: string;
    heading: string;
    body: string;
    checklist: Array<string>;
  }>;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0] {    siteName,    defaultSeoTitle,    defaultSeoDescription,    defaultSeoImage,    businessName,    contactEmail,    bookingSubdomainUrl,    socialLinks[] {      platform,      url    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  siteName: string;
  defaultSeoTitle: string | null;
  defaultSeoDescription: string | null;
  defaultSeoImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  businessName: string | null;
  contactEmail: string | null;
  bookingSubdomainUrl: string | null;
  socialLinks: Array<{
    platform:
      | "facebook"
      | "instagram"
      | "linkedin"
      | "tiktok"
      | "tripadvisor"
      | "whatsapp"
      | "x"
      | "youtube";
    url: string;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer" && _id == "footer"][0] {    tagline,    columns[] {      title,      links[] {        label,        href      }    },    copyrightText  }
export type FOOTER_QUERY_RESULT = {
  tagline: string | null;
  columns: Array<{
    title: string;
    links: Array<{
      label: string;
      href: string;
    }> | null;
  }> | null;
  copyrightText: string | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation" && _id == "navigation"][0] {    guestNavLinks[] {      label,      href    },    landlordNavLinks[] {      label,      href    }  }
export type NAVIGATION_QUERY_RESULT = {
  guestNavLinks: Array<{
    label: string;
    href: string;
  }> | null;
  landlordNavLinks: Array<{
    label: string;
    href: string;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PRIVACY_POLICY_QUERY
// Query: *[_type == "privacyPolicyPage" && _id == "privacyPolicyPage"][0] {    title,    lastUpdated,    body,      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type PRIVACY_POLICY_QUERY_RESULT = {
  title: string;
  lastUpdated: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo: {
    title: string;
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: TERMS_PAGE_QUERY
// Query: *[_type == "termsPage" && _id == "termsPage"][0] {    title,    lastUpdated,    body,      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type TERMS_PAGE_QUERY_RESULT = {
  title: string;
  lastUpdated: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo: {
    title: string;
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: HERO_SECTION_QUERY
// Query: *[_type == "heroSection" && _id == "heroSection"][0] {    eyebrow,    heading,    body,    subBody,    image,    primaryCtaLabel,    primaryCtaUrl,    secondaryCtaLabel,    secondaryCtaUrl  }
export type HERO_SECTION_QUERY_RESULT = {
  eyebrow: string | null;
  heading: string;
  body: string | null;
  subBody: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  primaryCtaLabel: string | null;
  primaryCtaUrl: string | null;
  secondaryCtaLabel: string | null;
  secondaryCtaUrl: string | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: HOSTS_MODULE_QUERY
// Query: *[_type == "hostsModule" && _id == "hostsModule"][0] {    eyebrow,    heading,    body,    commissionRate,    commissionLabel,    commissionSuffix,    commissionNote,    ctaLabel,    ctaUrl,    stepperEyebrow,    stepperHeading,    steps[] {      title,      bullets,      image    },    marqueeHeading,    marqueeSubtext  }
export type HOSTS_MODULE_QUERY_RESULT = {
  eyebrow: string | null;
  heading: string;
  body: string | null;
  commissionRate: number;
  commissionLabel: string | null;
  commissionSuffix: string | null;
  commissionNote: string | null;
  ctaLabel: string | null;
  ctaUrl: string | null;
  stepperEyebrow: string | null;
  stepperHeading: string | null;
  steps: Array<{
    title: string;
    bullets: Array<string>;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  }>;
  marqueeHeading: string | null;
  marqueeSubtext: string | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: CORPORATE_STAYS_PAGE_QUERY
// Query: *[_type == "corporateStaysPage" && _id == "corporateStaysPage"][0] {    heroBadge,    heroHeading,    heroBody,    heroPrimaryCtaLabel,    heroSecondaryCtaLabel,    heroFacts,    heroImages,    whoEyebrow,    whoHeading,    whoBody,    whoCards[] {      title,      body,      image    },    howEyebrow,    howHeading,    howBody,    howSteps[] {      title,      body    },    coverageEyebrow,    coverageHeading,    coverageAreas[] {      county,      live,      body    },    coverageNote,    includedEyebrow,    includedHeading,    includedFeatures[] {      title,      body,      icon    },    partnerEyebrow,    partnerHeading,    partnerBody,    partnerCtaLabel,    partnerCtaUrl,    faqEyebrow,    faqHeading,    faqs[] {      question,      answer    },    closingHeading,    closingBody,      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type CORPORATE_STAYS_PAGE_QUERY_RESULT = {
  heroBadge: string | null;
  heroHeading: string;
  heroBody: string | null;
  heroPrimaryCtaLabel: string | null;
  heroSecondaryCtaLabel: string | null;
  heroFacts: Array<string> | null;
  heroImages: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }> | null;
  whoEyebrow: string | null;
  whoHeading: string | null;
  whoBody: string | null;
  whoCards: Array<{
    title: string;
    body: string;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  }> | null;
  howEyebrow: string | null;
  howHeading: string | null;
  howBody: string | null;
  howSteps: Array<{
    title: string;
    body: string;
  }> | null;
  coverageEyebrow: string | null;
  coverageHeading: string | null;
  coverageAreas: Array<{
    county: string;
    live: boolean | null;
    body: string;
  }> | null;
  coverageNote: string | null;
  includedEyebrow: string | null;
  includedHeading: string | null;
  includedFeatures: Array<{
    title: string;
    body: string;
    icon: "clipboard" | "contact" | "sofa" | "wifi";
  }> | null;
  partnerEyebrow: string | null;
  partnerHeading: string | null;
  partnerBody: string | null;
  partnerCtaLabel: string | null;
  partnerCtaUrl: string | null;
  faqEyebrow: string | null;
  faqHeading: string | null;
  faqs: Array<{
    question: string;
    answer: string;
  }> | null;
  closingHeading: string | null;
  closingBody: string | null;
  seo: {
    title: string | "";
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0] {    heroBadge,    heroHeading,    heroImage,    introParagraph1,    introParagraph2,    introParagraph3,    whatWeDoEyebrow,    whatWeDoHeading,    whatWeDoItems[] {      title,      body    },    coverageEyebrow,    coverageHeading,    coverageBody,    coverageImage,    regions[] {      name,      status,      muted    },    staysHeading,    featuredStays[] {      name,      href,      description    },    teamEyebrow,    teamHeading,    teamIntro,    teamMembers[] {      name,      title,      plainTitle,      bio,      photo    },    workWithUsEyebrow,    workWithUsHeading,    workWithUsIntro,    workWithUsCategories[] {      title,      body    },    workWithUsPartnerNote,    workWithUsContactLine,    ownershipHeading,    ownershipBody,    ownershipCroLinkLabel,    ownershipCroLinkUrl,    reachUsHeading,    reachUsEmail,    reachUsWhatsapp,    reachUsWhatsappUrl,    reachUsInstagramHandle,    reachUsInstagramUrl,    faqHeading,    faqs[] {      question,      answer    },      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  heroBadge: string | null;
  heroHeading: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  introParagraph1: string | null;
  introParagraph2: string | null;
  introParagraph3: string | null;
  whatWeDoEyebrow: string | null;
  whatWeDoHeading: string | null;
  whatWeDoItems: Array<{
    title: string;
    body: string;
  }> | null;
  coverageEyebrow: string | null;
  coverageHeading: string | null;
  coverageBody: string | null;
  coverageImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  regions: Array<{
    name: string;
    status: string;
    muted: boolean | null;
  }> | null;
  staysHeading: string | null;
  featuredStays: Array<{
    name: string;
    href: string;
    description: string;
  }> | null;
  teamEyebrow: string | null;
  teamHeading: string | null;
  teamIntro: string | null;
  teamMembers: Array<{
    name: string;
    title: string;
    plainTitle: string;
    bio: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }> | null;
  workWithUsEyebrow: string | null;
  workWithUsHeading: string | null;
  workWithUsIntro: string | null;
  workWithUsCategories: Array<{
    title: string;
    body: string;
  }> | null;
  workWithUsPartnerNote: string | null;
  workWithUsContactLine: string | null;
  ownershipHeading: string | null;
  ownershipBody: string | null;
  ownershipCroLinkLabel: string | null;
  ownershipCroLinkUrl: string | null;
  reachUsHeading: string | null;
  reachUsEmail: string | null;
  reachUsWhatsapp: string | null;
  reachUsWhatsappUrl: string | null;
  reachUsInstagramHandle: string | null;
  reachUsInstagramUrl: string | null;
  faqHeading: string | null;
  faqs: Array<{
    question: string;
    answer: string;
  }> | null;
  seo: {
    title: string | "";
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: CORPORATE_ONBOARDED_PROPERTIES_QUERY
// Query: *[_type == "propertyPage" && defined(slug.current)] | order(name asc) [0...8] {    _id,    name,    "slug": slug.current,    location,    "coverImage": gallery[0]  }
export type CORPORATE_ONBOARDED_PROPERTIES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  location: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: PARTNERS_PAGE_QUERY
// Query: *[_type == "partnersPage" && _id == "partnersPage"][0] {    heroBadge,    heroHeading,    heroImage,    introParagraph1,    introParagraph2,    introParagraph3,    tiersEyebrow,    tiersHeading,    tiers[] {      title,      body    },    tiersNote,    whoWeWantEyebrow,    whoWeWantHeading,    whoWeWantCategories[] {      title,      body,      tag    },    spotlightHeading,    spotlightBody,    spotlightImage,    directoryEyebrow,    directoryHeading,    becomePartnerEyebrow,    becomePartnerHeading,    becomePartnerIntro,      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type PARTNERS_PAGE_QUERY_RESULT = {
  heroBadge: string | null;
  heroHeading: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  introParagraph1: string | null;
  introParagraph2: string | null;
  introParagraph3: string | null;
  tiersEyebrow: string | null;
  tiersHeading: string | null;
  tiers: Array<{
    title: string;
    body: string;
  }> | null;
  tiersNote: string | null;
  whoWeWantEyebrow: string | null;
  whoWeWantHeading: string | null;
  whoWeWantCategories: Array<{
    title: string;
    body: string;
    tag:
      | "cleaning"
      | "food-drink"
      | "hospitality-days-out"
      | "photography"
      | "social-content"
      | "tours-experiences";
  }> | null;
  spotlightHeading: string | null;
  spotlightBody: string | null;
  spotlightImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  directoryEyebrow: string | null;
  directoryHeading: string | null;
  becomePartnerEyebrow: string | null;
  becomePartnerHeading: string | null;
  becomePartnerIntro: string | null;
  seo: {
    title: string | "";
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PARTNERS_QUERY
// Query: *[_type == "partner"] | order(featured desc, name asc) {    _id,    name,    "slug": slug.current,    tagline,    category,    description,    href,    featured,    image  }
export type PARTNERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string | null;
  tagline: string;
  category:
    | "cleaning"
    | "food-drink"
    | "hospitality-days-out"
    | "photography"
    | "social-content"
    | "tours-experiences";
  description: string;
  href: string;
  featured: boolean | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: PARTNER_BY_SLUG_QUERY
// Query: *[_type == "partner" && featured == true && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    tagline,    category,    description,    href,    featured,    image,    profileIntro,    profileBody  }
export type PARTNER_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string | null;
  tagline: string;
  category:
    | "cleaning"
    | "food-drink"
    | "hospitality-days-out"
    | "photography"
    | "social-content"
    | "tours-experiences";
  description: string;
  href: string;
  featured: boolean | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  profileIntro: string | null;
  profileBody: string | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: FEATURED_PARTNER_SLUGS_QUERY
// Query: *[_type == "partner" && featured == true && defined(slug.current)][].slug.current
export type FEATURED_PARTNER_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../web/src/sanity/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: {  "properties": *[_type == "propertyPage" && defined(slug.current)] | order(name asc) [0...3] {    _id, name, "slug": slug.current, location, shortDescription, sleeps,    "coverImage": gallery[0], "gallery": gallery[0...3]  },  "areas": *[_type == "areaGuide" && defined(slug.current)] | order(areaName asc) [0...4] {    _id, areaName, "slug": slug.current, heroImage, introduction  }}
export type HOMEPAGE_QUERY_RESULT = {
  properties: Array<{
    _id: string;
    name: string;
    slug: string;
    location: string;
    shortDescription: string | null;
    sleeps: number | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
      _key: string;
    } | null;
    gallery: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
      _key: string;
    }> | null;
  }>;
  areas: Array<{
    _id: string;
    areaName: string;
    slug: string;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    introduction: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  }>;
};

// Source: ../web/src/sanity/queries.ts
// Variable: LANDING_PAGE_QUERY
// Query: *[_type == "landingPage" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    heroEyebrow,    heroHeadline,    heroSubtext,    heroTags,    heroImage,    primaryCtaLabel,    primaryCtaUrl,    secondaryCtaLabel,    secondaryCtaUrl,    marqueeItems,    distanceStat,    distanceLabel,    destinationName,    distanceText,    geographyHeading,    proximityStats[] {      value,      label    },    directBookingBadge,    directBookingHeadline,    directBookingText,    directBookingSavingsPercent,    directBookingComparisonNote,    featuredProperty-> {      _id,      name,      "slug": slug.current,      location,      shortDescription,      sleeps,      bedrooms,      beds,      bathrooms,      reviewScore,      reviewCount,      amenities,      roomTypes,      "coverImage": gallery[0],      "gallery": gallery[0...3],      uplistingPropertySlug    },    infoSections[] {      eyebrow,      heading,      body,      layout,      items[] {        title,        description,        tag,        image,        link      }    },    pricingTiers[] {      amount,      label    },    pricingNote,    pricingLink,    pricingLinkLabel,    itineraryEyebrow,    itineraryHeading,    itineraryText,    itineraryDays[] {      dayLabel,      items[] {        time,        title,        description      }    },    relatedAreaGuide-> {      areaName,      "slug": slug.current,      thingsToDo    },    finalCtaHeadline,    finalCtaText,    finalCtaSecondaryLabel,    finalCtaSecondaryUrl,    stickyBarEnabled,      "seo": {    "title": coalesce(seoTitle, name, title, areaName, ""),    "description": coalesce(seoDescription, shortDescription, excerpt, ""),    "image": seoImage,    "noIndex": noIndex == true  }  }
export type LANDING_PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  heroEyebrow: string | null;
  heroHeadline: string;
  heroSubtext: string | null;
  heroTags: Array<string> | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  primaryCtaLabel: string | null;
  primaryCtaUrl: string | null;
  secondaryCtaLabel: string | null;
  secondaryCtaUrl: string | null;
  marqueeItems: Array<string> | null;
  distanceStat: string | null;
  distanceLabel: string | null;
  destinationName: string | null;
  distanceText: string | null;
  geographyHeading: string | null;
  proximityStats: Array<{
    value: string;
    label: string;
  }> | null;
  directBookingBadge: string | null;
  directBookingHeadline: string | null;
  directBookingText: string | null;
  directBookingSavingsPercent: number | null;
  directBookingComparisonNote: string | null;
  featuredProperty: {
    _id: string;
    name: string;
    slug: string;
    location: string;
    shortDescription: string | null;
    sleeps: number | null;
    bedrooms: number | null;
    beds: number | null;
    bathrooms: number | null;
    reviewScore: number | null;
    reviewCount: number | null;
    amenities: Array<string> | null;
    roomTypes: Array<{
      name: string;
      roomId?: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      bedConfiguration?: string;
      guests: number;
      _type: "roomType";
      _key: string;
    }> | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
      _key: string;
    } | null;
    gallery: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
      _key: string;
    }> | null;
    uplistingPropertySlug: string;
  } | null;
  infoSections: Array<{
    eyebrow: string | null;
    heading: string | null;
    body: string | null;
    layout: "cards" | "photoGrid" | null;
    items: Array<{
      title: string | null;
      description: string | null;
      tag: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      link: string | null;
    }> | null;
  }> | null;
  pricingTiers: Array<{
    amount: string;
    label: string;
  }> | null;
  pricingNote: string | null;
  pricingLink: string | null;
  pricingLinkLabel: string | null;
  itineraryEyebrow: string | null;
  itineraryHeading: string | null;
  itineraryText: string | null;
  itineraryDays: Array<{
    dayLabel: string;
    items: Array<{
      time: string | null;
      title: string;
      description: string | null;
    }> | null;
  }> | null;
  relatedAreaGuide: {
    areaName: string;
    slug: string;
    thingsToDo: Array<{
      title: string;
      category: "Explore" | "Food" | "Things to Do" | "Transport";
      tag?: string;
      description?: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      link?: string;
      _type: "activity";
      _key: string;
    }> | null;
  } | null;
  finalCtaHeadline: string | null;
  finalCtaText: string | null;
  finalCtaSecondaryLabel: string | null;
  finalCtaSecondaryUrl: string | null;
  stickyBarEnabled: boolean | null;
  seo: {
    title: string;
    description: string | "";
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: SITEMAP_QUERY
// Query: *[_type in ["blogPost", "propertyPage", "areaGuide", "landlordPage", "landingPage"] && defined(slug.current) && noIndex != true] {    "href": select(      _type == "blogPost" => "/blog/" + slug.current,      _type == "propertyPage" => "/stays/" + slug.current,      _type == "areaGuide" => "/areas/" + slug.current,      _type == "landlordPage" => "/landlords/" + slug.current,      "/" + slug.current    ),    _updatedAt  }
export type SITEMAP_QUERY_RESULT = Array<{
  href: string;
  _updatedAt: string;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: SITEMAP_SINGLETONS_QUERY
// Query: *[_type in ["aboutPage", "corporateStaysPage", "privacyPolicyPage", "termsPage"]] {    "href": select(      _type == "aboutPage" => "/about",      _type == "corporateStaysPage" => "/corporate-stays",      _type == "privacyPolicyPage" => "/privacy-policy",      _type == "termsPage" => "/terms-and-conditions"    ),    _updatedAt,    "noIndex": noIndex == true  }
export type SITEMAP_SINGLETONS_QUERY_RESULT = Array<
  | {
      href: "/about";
      _updatedAt: string;
      noIndex: boolean | false;
    }
  | {
      href: "/corporate-stays";
      _updatedAt: string;
      noIndex: boolean | false;
    }
  | {
      href: "/privacy-policy";
      _updatedAt: string;
      noIndex: boolean | false;
    }
  | {
      href: "/terms-and-conditions";
      _updatedAt: string;
      noIndex: boolean | false;
    }
>;

// Source: ../web/src/sanity/queries.ts
// Variable: LLMS_TXT_QUERY
// Query: {  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0] {    siteName,    defaultSeoDescription,    businessName,    contactEmail,    socialLinks  },  "entries": *[_type in ["blogPost", "propertyPage", "areaGuide", "landlordPage", "landingPage"] && defined(slug.current) && noIndex != true] {    _type,    "href": select(      _type == "blogPost" => "/blog/" + slug.current,      _type == "propertyPage" => "/stays/" + slug.current,      _type == "areaGuide" => "/areas/" + slug.current,      _type == "landlordPage" => "/landlords/" + slug.current,      "/" + slug.current    ),    "title": coalesce(name, title, areaName, ""),    "summary": coalesce(shortDescription, excerpt, heroStatement, pt::text(introduction), "")  }}
export type LLMS_TXT_QUERY_RESULT = {
  settings: {
    siteName: string;
    defaultSeoDescription: string | null;
    businessName: string | null;
    contactEmail: string | null;
    socialLinks: Array<{
      platform:
        | "facebook"
        | "instagram"
        | "linkedin"
        | "tiktok"
        | "tripadvisor"
        | "whatsapp"
        | "x"
        | "youtube";
      url: string;
      _type: "socialLink";
      _key: string;
    }> | null;
  } | null;
  entries: Array<
    | {
        _type: "areaGuide";
        href: string;
        title: string;
        summary: string;
      }
    | {
        _type: "blogPost";
        href: string;
        title: string;
        summary: string;
      }
    | {
        _type: "landingPage";
        href: string;
        title: string;
        summary: string;
      }
    | {
        _type: "landlordPage";
        href: string;
        title: string;
        summary: string;
      }
    | {
        _type: "propertyPage";
        href: string;
        title: string;
        summary: string;
      }
  >;
};

// Source: ../web/src/sanity/queries.ts
// Variable: COUNTY_PRICING_STATS_QUERY
// Query: *[_type == "countyPricingStats" && live == true] {    county,    adr,    occupancy,    annualRevenue,    statsSourceNote,    realExample,    drivers,    faqs  }
export type COUNTY_PRICING_STATS_QUERY_RESULT = Array<{
  county:
    | "Antrim"
    | "Armagh"
    | "Carlow"
    | "Cavan"
    | "Clare"
    | "Cork"
    | "Derry / Londonderry"
    | "Donegal"
    | "Down"
    | "Dublin"
    | "Fermanagh"
    | "Galway"
    | "Kerry"
    | "Kildare"
    | "Kilkenny"
    | "Laois"
    | "Leitrim"
    | "Limerick"
    | "Longford"
    | "Louth"
    | "Mayo"
    | "Meath"
    | "Monaghan"
    | "Offaly"
    | "Roscommon"
    | "Sligo"
    | "Tipperary"
    | "Tyrone"
    | "Waterford"
    | "Westmeath"
    | "Wexford"
    | "Wicklow";
  adr: number;
  occupancy: number;
  annualRevenue: number;
  statsSourceNote: string;
  realExample: {
    propertyName: string;
    propertyLocation: string;
    beforeLabel: string;
    beforeOccupancy: number;
    afterLabel: string;
    afterOccupancy: number;
    note: string;
  } | null;
  drivers: Array<string> | null;
  faqs: Array<{
    question: string;
    answer: string;
    _type: "faq";
    _key: string;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "blogPost" && defined(slug.current)] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    coverImage,\n    publishedAt,\n    author,\n    tags\n  }\n': BLOG_POSTS_QUERY_RESULT;
    '\n  *[_type == "blogPost" && defined(slug.current) && "landlord" in tags] | order(publishedAt desc) [0...3] {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    coverImage,\n    publishedAt,\n    author,\n    tags\n  }\n': LANDLORD_BLOG_POSTS_QUERY_RESULT;
    '\n  *[_type == "blogPost" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    coverImage,\n    body,\n    publishedAt,\n    author,\n    tags,\n    relatedAreaGuides[]-> {\n      _id,\n      areaName,\n      "slug": slug.current,\n      heroImage\n    },\n    promotedProperty-> {\n      _id,\n      name,\n      "slug": slug.current,\n      location,\n      shortDescription,\n      priceLabel,\n      "coverImage": gallery[0]\n    },\n    "relatedPosts": *[_type == "blogPost" && defined(slug.current) && _id != ^._id] | order(publishedAt desc) [0...3] {\n      _id,\n      title,\n      "slug": slug.current,\n      coverImage,\n      publishedAt\n    },\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': BLOG_POST_QUERY_RESULT;
    '\n  *[_type == "propertyPage" && defined(slug.current)] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    location,\n    shortDescription,\n    sleeps,\n    "coverImage": gallery[0],\n    uplistingPropertySlug,\n    roomTypes[] {\n      name,\n      roomId,\n      image,\n      bedConfiguration,\n      guests\n    }\n  }\n': PROPERTY_PAGES_QUERY_RESULT;
    '\n  *[_type == "propertyPage" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    location,\n    locationLink,\n    shortDescription,\n    fullDescription,\n    gallery,\n    galleryPromotion {\n      enabled,\n      highlights[] {\n        headline,\n        description,\n        image {\n          ...,\n          alt\n        },\n        supportingImages[] {\n          ...,\n          alt\n        },\n        ctaLabel,\n        ctaHref\n      },\n      delaySeconds,\n      autoplaySeconds\n    },\n    "videoUrl": video.asset->url,\n    "videoMimeType": video.asset->mimeType,\n    roomTypes,\n    amenities,\n    sleeps,\n    priceLabel,\n    bedrooms,\n    beds,\n    bathrooms,\n    propertyType,\n    reviewScore,\n    reviewCount,\n    reviewCategories,\n    uplistingPropertySlug,\n    uplistingPropertyId,\n    faqs,\n    relatedAreaGuides[]-> {\n      _id,\n      areaName,\n      "slug": slug.current,\n      heroImage,\n      introduction\n    },\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': PROPERTY_PAGE_QUERY_RESULT;
    '\n  *[_type == "propertyPage" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    location,\n    sleeps,\n    "coverImage": gallery[0],\n    uplistingPropertyId,\n    "addOns": *[_type == "addOn" && enabled != false && references(^._id)] {\n      _id,\n      name,\n      description,\n      price,\n      image\n    }\n  }\n': PROPERTY_BOOKING_QUERY_RESULT;
    '\n  *[_type == "areaGuide" && defined(slug.current)] | order(areaName asc) {\n    _id,\n    areaName,\n    "slug": slug.current,\n    heroImage,\n    introduction\n  }\n': AREA_GUIDES_QUERY_RESULT;
    '\n  *[_type == "areaGuide" && slug.current == $slug][0] {\n    _id,\n    areaName,\n    "slug": slug.current,\n    heroImage,\n    introduction,\n    thingsToDo,\n    travelNotes,\n    faqs,\n    featuredProperties[]-> {\n      _id,\n      name,\n      "slug": slug.current,\n      location,\n      shortDescription,\n      sleeps,\n      "coverImage": gallery[0],\n      "gallery": gallery[0...3],\n      uplistingPropertySlug\n    },\n    "relatedBlogPosts": *[_type == "blogPost" && references(^._id)] {\n      _id,\n      title,\n      "slug": slug.current,\n      excerpt,\n      coverImage\n    },\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': AREA_GUIDE_QUERY_RESULT;
    '\n  *[_type == "landlordPage" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    heroStatement,\n    proofPoints,\n    body,\n    faqs,\n    ctaLabel,\n    ctaUrl,\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': LANDLORD_PAGE_QUERY_RESULT;
    '\n  *[_type == "landlordPage" && defined(slug.current)] | order(_createdAt asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    heroStatement,\n    proofPoints,\n    body,\n    faqs,\n    ctaLabel,\n    ctaUrl,\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': LANDLORD_PAGES_QUERY_RESULT;
    '\n  *[_type == "audienceTabs" && _id == "audienceTabs"][0] {\n    eyebrow,\n    tabs[] {\n      label,\n      heading,\n      body,\n      checklist\n    }\n  }\n': AUDIENCE_TABS_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0] {\n    siteName,\n    defaultSeoTitle,\n    defaultSeoDescription,\n    defaultSeoImage,\n    businessName,\n    contactEmail,\n    bookingSubdomainUrl,\n    socialLinks[] {\n      platform,\n      url\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "footer" && _id == "footer"][0] {\n    tagline,\n    columns[] {\n      title,\n      links[] {\n        label,\n        href\n      }\n    },\n    copyrightText\n  }\n': FOOTER_QUERY_RESULT;
    '\n  *[_type == "navigation" && _id == "navigation"][0] {\n    guestNavLinks[] {\n      label,\n      href\n    },\n    landlordNavLinks[] {\n      label,\n      href\n    }\n  }\n': NAVIGATION_QUERY_RESULT;
    '\n  *[_type == "privacyPolicyPage" && _id == "privacyPolicyPage"][0] {\n    title,\n    lastUpdated,\n    body,\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': PRIVACY_POLICY_QUERY_RESULT;
    '\n  *[_type == "termsPage" && _id == "termsPage"][0] {\n    title,\n    lastUpdated,\n    body,\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': TERMS_PAGE_QUERY_RESULT;
    '\n  *[_type == "heroSection" && _id == "heroSection"][0] {\n    eyebrow,\n    heading,\n    body,\n    subBody,\n    image,\n    primaryCtaLabel,\n    primaryCtaUrl,\n    secondaryCtaLabel,\n    secondaryCtaUrl\n  }\n': HERO_SECTION_QUERY_RESULT;
    '\n  *[_type == "hostsModule" && _id == "hostsModule"][0] {\n    eyebrow,\n    heading,\n    body,\n    commissionRate,\n    commissionLabel,\n    commissionSuffix,\n    commissionNote,\n    ctaLabel,\n    ctaUrl,\n    stepperEyebrow,\n    stepperHeading,\n    steps[] {\n      title,\n      bullets,\n      image\n    },\n    marqueeHeading,\n    marqueeSubtext\n  }\n': HOSTS_MODULE_QUERY_RESULT;
    '\n  *[_type == "corporateStaysPage" && _id == "corporateStaysPage"][0] {\n    heroBadge,\n    heroHeading,\n    heroBody,\n    heroPrimaryCtaLabel,\n    heroSecondaryCtaLabel,\n    heroFacts,\n    heroImages,\n    whoEyebrow,\n    whoHeading,\n    whoBody,\n    whoCards[] {\n      title,\n      body,\n      image\n    },\n    howEyebrow,\n    howHeading,\n    howBody,\n    howSteps[] {\n      title,\n      body\n    },\n    coverageEyebrow,\n    coverageHeading,\n    coverageAreas[] {\n      county,\n      live,\n      body\n    },\n    coverageNote,\n    includedEyebrow,\n    includedHeading,\n    includedFeatures[] {\n      title,\n      body,\n      icon\n    },\n    partnerEyebrow,\n    partnerHeading,\n    partnerBody,\n    partnerCtaLabel,\n    partnerCtaUrl,\n    faqEyebrow,\n    faqHeading,\n    faqs[] {\n      question,\n      answer\n    },\n    closingHeading,\n    closingBody,\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': CORPORATE_STAYS_PAGE_QUERY_RESULT;
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0] {\n    heroBadge,\n    heroHeading,\n    heroImage,\n    introParagraph1,\n    introParagraph2,\n    introParagraph3,\n    whatWeDoEyebrow,\n    whatWeDoHeading,\n    whatWeDoItems[] {\n      title,\n      body\n    },\n    coverageEyebrow,\n    coverageHeading,\n    coverageBody,\n    coverageImage,\n    regions[] {\n      name,\n      status,\n      muted\n    },\n    staysHeading,\n    featuredStays[] {\n      name,\n      href,\n      description\n    },\n    teamEyebrow,\n    teamHeading,\n    teamIntro,\n    teamMembers[] {\n      name,\n      title,\n      plainTitle,\n      bio,\n      photo\n    },\n    workWithUsEyebrow,\n    workWithUsHeading,\n    workWithUsIntro,\n    workWithUsCategories[] {\n      title,\n      body\n    },\n    workWithUsPartnerNote,\n    workWithUsContactLine,\n    ownershipHeading,\n    ownershipBody,\n    ownershipCroLinkLabel,\n    ownershipCroLinkUrl,\n    reachUsHeading,\n    reachUsEmail,\n    reachUsWhatsapp,\n    reachUsWhatsappUrl,\n    reachUsInstagramHandle,\n    reachUsInstagramUrl,\n    faqHeading,\n    faqs[] {\n      question,\n      answer\n    },\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "propertyPage" && defined(slug.current)] | order(name asc) [0...8] {\n    _id,\n    name,\n    "slug": slug.current,\n    location,\n    "coverImage": gallery[0]\n  }\n': CORPORATE_ONBOARDED_PROPERTIES_QUERY_RESULT;
    '\n  *[_type == "partnersPage" && _id == "partnersPage"][0] {\n    heroBadge,\n    heroHeading,\n    heroImage,\n    introParagraph1,\n    introParagraph2,\n    introParagraph3,\n    tiersEyebrow,\n    tiersHeading,\n    tiers[] {\n      title,\n      body\n    },\n    tiersNote,\n    whoWeWantEyebrow,\n    whoWeWantHeading,\n    whoWeWantCategories[] {\n      title,\n      body,\n      tag\n    },\n    spotlightHeading,\n    spotlightBody,\n    spotlightImage,\n    directoryEyebrow,\n    directoryHeading,\n    becomePartnerEyebrow,\n    becomePartnerHeading,\n    becomePartnerIntro,\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': PARTNERS_PAGE_QUERY_RESULT;
    '\n  *[_type == "partner"] | order(featured desc, name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    tagline,\n    category,\n    description,\n    href,\n    featured,\n    image\n  }\n': PARTNERS_QUERY_RESULT;
    '\n  *[_type == "partner" && featured == true && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    tagline,\n    category,\n    description,\n    href,\n    featured,\n    image,\n    profileIntro,\n    profileBody\n  }\n': PARTNER_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "partner" && featured == true && defined(slug.current)][].slug.current\n': FEATURED_PARTNER_SLUGS_QUERY_RESULT;
    '{\n  "properties": *[_type == "propertyPage" && defined(slug.current)] | order(name asc) [0...3] {\n    _id, name, "slug": slug.current, location, shortDescription, sleeps,\n    "coverImage": gallery[0], "gallery": gallery[0...3]\n  },\n  "areas": *[_type == "areaGuide" && defined(slug.current)] | order(areaName asc) [0...4] {\n    _id, areaName, "slug": slug.current, heroImage, introduction\n  }\n}': HOMEPAGE_QUERY_RESULT;
    '\n  *[_type == "landingPage" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    heroEyebrow,\n    heroHeadline,\n    heroSubtext,\n    heroTags,\n    heroImage,\n    primaryCtaLabel,\n    primaryCtaUrl,\n    secondaryCtaLabel,\n    secondaryCtaUrl,\n    marqueeItems,\n    distanceStat,\n    distanceLabel,\n    destinationName,\n    distanceText,\n    geographyHeading,\n    proximityStats[] {\n      value,\n      label\n    },\n    directBookingBadge,\n    directBookingHeadline,\n    directBookingText,\n    directBookingSavingsPercent,\n    directBookingComparisonNote,\n    featuredProperty-> {\n      _id,\n      name,\n      "slug": slug.current,\n      location,\n      shortDescription,\n      sleeps,\n      bedrooms,\n      beds,\n      bathrooms,\n      reviewScore,\n      reviewCount,\n      amenities,\n      roomTypes,\n      "coverImage": gallery[0],\n      "gallery": gallery[0...3],\n      uplistingPropertySlug\n    },\n    infoSections[] {\n      eyebrow,\n      heading,\n      body,\n      layout,\n      items[] {\n        title,\n        description,\n        tag,\n        image,\n        link\n      }\n    },\n    pricingTiers[] {\n      amount,\n      label\n    },\n    pricingNote,\n    pricingLink,\n    pricingLinkLabel,\n    itineraryEyebrow,\n    itineraryHeading,\n    itineraryText,\n    itineraryDays[] {\n      dayLabel,\n      items[] {\n        time,\n        title,\n        description\n      }\n    },\n    relatedAreaGuide-> {\n      areaName,\n      "slug": slug.current,\n      thingsToDo\n    },\n    finalCtaHeadline,\n    finalCtaText,\n    finalCtaSecondaryLabel,\n    finalCtaSecondaryUrl,\n    stickyBarEnabled,\n    \n  "seo": {\n    "title": coalesce(seoTitle, name, title, areaName, ""),\n    "description": coalesce(seoDescription, shortDescription, excerpt, ""),\n    "image": seoImage,\n    "noIndex": noIndex == true\n  }\n\n  }\n': LANDING_PAGE_QUERY_RESULT;
    '\n  *[_type in ["blogPost", "propertyPage", "areaGuide", "landlordPage", "landingPage"] && defined(slug.current) && noIndex != true] {\n    "href": select(\n      _type == "blogPost" => "/blog/" + slug.current,\n      _type == "propertyPage" => "/stays/" + slug.current,\n      _type == "areaGuide" => "/areas/" + slug.current,\n      _type == "landlordPage" => "/landlords/" + slug.current,\n      "/" + slug.current\n    ),\n    _updatedAt\n  }\n': SITEMAP_QUERY_RESULT;
    '\n  *[_type in ["aboutPage", "corporateStaysPage", "privacyPolicyPage", "termsPage"]] {\n    "href": select(\n      _type == "aboutPage" => "/about",\n      _type == "corporateStaysPage" => "/corporate-stays",\n      _type == "privacyPolicyPage" => "/privacy-policy",\n      _type == "termsPage" => "/terms-and-conditions"\n    ),\n    _updatedAt,\n    "noIndex": noIndex == true\n  }\n': SITEMAP_SINGLETONS_QUERY_RESULT;
    '\n{\n  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0] {\n    siteName,\n    defaultSeoDescription,\n    businessName,\n    contactEmail,\n    socialLinks\n  },\n  "entries": *[_type in ["blogPost", "propertyPage", "areaGuide", "landlordPage", "landingPage"] && defined(slug.current) && noIndex != true] {\n    _type,\n    "href": select(\n      _type == "blogPost" => "/blog/" + slug.current,\n      _type == "propertyPage" => "/stays/" + slug.current,\n      _type == "areaGuide" => "/areas/" + slug.current,\n      _type == "landlordPage" => "/landlords/" + slug.current,\n      "/" + slug.current\n    ),\n    "title": coalesce(name, title, areaName, ""),\n    "summary": coalesce(shortDescription, excerpt, heroStatement, pt::text(introduction), "")\n  }\n}\n': LLMS_TXT_QUERY_RESULT;
    '\n  *[_type == "countyPricingStats" && live == true] {\n    county,\n    adr,\n    occupancy,\n    annualRevenue,\n    statsSourceNote,\n    realExample,\n    drivers,\n    faqs\n  }\n': COUNTY_PRICING_STATS_QUERY_RESULT;
  }
}
